---
permalink: protect/configure-array-manager.html 
sidebar: sidebar 
keywords:  
summary: '您可以使用VMware Live Site Recovery中的阵列管理器向导配置Storage Replication Adapter \(SRA\)、以便在VMware Live Site Recovery和Storage Virtual Machine \(SVM\)之间进行交互。' 
---
= 使用阵列管理器配置 SRA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用VMware Live Site Recovery中的阵列管理器向导配置Storage Replication Adapter (SRA)、以便在VMware Live Site Recovery和Storage Virtual Machine (SVM)之间进行交互。

.开始之前
* 您应已在VMware Live Site Recovery中将受保护站点和恢复站点配对。
* 在配置阵列管理器之前、您应已配置已启用的存储。
* 您应已在受保护站点和恢复站点之间配置和复制SnapMirror关系。
* 要启用多租户、您应已启用SVM管理SVM。


SRA 支持集群级别的管理和 SVM 级别的管理。如果在集群级别添加存储、则可以发现集群中的所有SVM并对其执行操作。如果在 SVM 级别添加存储，则只能管理该特定 SVM 。

.步骤
. 在VMware Live Site Recovery中，选择*Array Manager*>*Add Array Manager*。
. 输入以下信息以描述VMware Live Site Recovery中的阵列：
+
.. 在 * 显示名称 * 字段中输入一个名称以标识阵列管理器。
.. 在 * SRA 类型 * 字段中，选择 * 适用于 ONTAP 的 NetApp 存储复制适配器 * 。
.. 输入要连接到集群或 SVM 的信息：
+
*** 如果要连接到集群，则应输入集群管理 LIF 。
*** 如果要直接连接到 SVM ，则应输入 SVM 管理 LIF 的 IP 地址。
+

NOTE: 在配置阵列管理器时、您应对存储系统使用与在适用于VMware vSphere的ONTAP工具中板载存储系统时使用的相同连接(IP地址)。例如、如果阵列管理器配置的范围为SVM、则应在SVM级别添加适用于VMware vSphere的ONTAP工具下的存储。



.. 如果要连接到集群，请在 * SVM name* 字段中输入 SVM 的名称。
+
您也可以将此字段留空。

.. 在 * 卷包含列表 * 字段中输入要发现的卷。
+
您可以在受保护站点输入源卷，并在恢复站点输入复制的目标卷。

+
例如、如果要发现与卷dst_vol1具有SnapMirror关系的卷src_vol1、则应在受保护站点字段中指定src_vol1、在恢复站点字段中指定dst_vol1。

.. * （可选） * 在 * 卷排除列表 * 字段中输入要从发现中排除的卷。
+
您可以在受保护站点输入源卷，并在恢复站点输入复制的目标卷。

+
例如、如果要排除与卷_dst_vol1_具有SnapMirror关系的卷_src_vol1_、则应在受保护站点字段中指定_src_vol1_、在恢复站点字段中指定_dst_vol1_。



. 选择 * 下一步 * 。
. 验证是否已发现阵列并显示在"Add Array Manager"(添加阵列管理器)窗口的底部，然后选择"*Complete"(完成)。


您可以使用相应的 SVM 管理 IP 地址和凭据对恢复站点执行相同的步骤。在添加阵列管理器向导的启用阵列对屏幕上，您应验证是否选择了正确的阵列对，并且该阵列对是否显示为已准备好启用。
