---
permalink: configure/discover-storage-systems-and-hosts.html 
sidebar: sidebar 
keywords:  
summary: 首次在vSphere Client中运行适用于VMware vSphere的ONTAP工具时、适用于VMware vSphere的ONTAP工具会发现ESXi主机、其LUN和NFS导出以及这些LUN和导出所属的NetApp存储系统。 
---
= 发现存储系统和主机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
首次在vSphere Client中运行适用于VMware vSphere的ONTAP工具时、ONTAP工具会发现ESXi主机、其LUN和NFS导出以及这些LUN和导出所属的NetApp存储系统。

.开始之前
* 所有ESXi主机均应已启动并连接。
* 要发现的所有Storage Virtual Machine (SVM)均应正在运行、并且每个集群节点应至少为正在使用的存储协议(NFS或iSCSI)配置一个数据LIF。


* 关于此任务 *

您可以随时发现新的存储系统或更新有关现有存储系统的信息，以获取最新的容量和配置信息。此外、您还可以修改适用于VMware vSphere的ONTAP工具用于登录到存储系统的凭据。

发现存储系统时、适用于VMware vSphere的ONTAP工具会从vCenter Server实例管理的ESXi主机收集信息。

.步骤
. 在vSphere Client主页中、选择*主机和集群*。
. 右键单击所需的数据中心，然后选择*Host tools*>*更新NetApp ONTAP Data*。
+
在*Confirm *(确认*)对话框中，确认您的选择。

. 选择已发现的状态为的存储控制器 `Authentication Failure`，然后选择*Actions*>*Modify*。
. 在*修改存储系统*对话框中填写所需信息。
. 对所有 `Authentication Failure`状态为的存储控制器重复步骤4和5。


发现过程完成后、请执行以下操作：

* 使用适用于VMware vSphere的ONTAP工具为在适配器设置列、MPIO设置列或NFS设置列中显示警报图标的主机配置ESXi主机设置。
* 提供存储系统凭据。

